allowed_features:
  - Дата регистрации
  - Пользователь
  - Услуга
  - Компонент услуги 1 уровня
  - Тип запроса
  - Описание 2
  - Критичность
  - Срочность
  - Приоритет
  - Класс обслуживания
  - Часовой пояс запроса

target: Кем решен (группа)
text_feature: Описание 2

forbidden_features:
  - Фактическое время выполнения
  - Фактическая длительность выполнения запроса (SLA)
  - Просрочен?*
  - Дата последнего изменения
  - Суммарное время реакции 1 линии
  - Суммарное время работы 1 линии
  - Суммарное время реакции 2 линии
  - Суммарное время работы 2 линии
  - Суммарное время реакции 3 линии
  - Суммарное время работы 3 линии
  - Суммарное время реакции 4 линии
  - Суммарное время работы 4 линии
  - Суммарное время уточнений
  - Результат работ
  - Количество уточнений
